server:
  port: 8081
  servlet:
    context-path: /fee-collection


spring:
  application:
    name: fee-collection
  datasource:
    url: jdbc:h2:mem:feecollectiondb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  springdoc:
    swagger-ui:
      path=/swagger-ui.html
    api-docs:
      path=/api-docs

  # Actuator
management:
  server:
    port: 8085
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
    health:
      enabled: true


